version: '3.7'

services:

   master:
      image: ghcr.io/lyl-radio/icecast:latest
      environment: 
         GENERATE_TEMPLATE: "true"

   relay:
      image: ghcr.io/lyl-radio/icecast:latest
      environment:
         GENERATE_TEMPLATE: "true"
         ENABLE_RELAY: "true"
         IC_RELAY_MASTER_SERVER: master
         IC_RELAY_MASTER_UPDATE_INTERVAL: 30